name: mtags
version: 0.1.0.0
github: dbaynard/mtags
author: "David Baynard <haskell@baynard.dev>"
maintainer: "David Baynard <haskell@baynard.dev>"
copyright: "2019–2020 David Baynard"
synopsis: Generate ctags-compatible tags for (pandoc) markdown files.
description: |
  See [README.md](https://github.com/dbaynard/mtags)
license: BSD-3-Clause OR Apache-2.0
category: Development

extra-source-files:
- ../README.md
- ../LICENSE

ghc-options:
- -Wall
- -Wincomplete-uni-patterns
- -Wincomplete-record-updates
- -Wcompat
- -Wnoncanonical-monad-instances

dependencies:
- base >= 4.12.0.0 && < 5
- rio

library:
  source-dirs: src
  exposed-modules:
  - MTags
  - MTags.Parser
  dependencies:
  - cmark
  - generic-lens
  - prettyprinter
  - raw-strings-qq
  - validity
  - validity-containers
  - validity-text

executables:
  mtags:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mtags
    - optparse-generic

tests:
  mtags-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mtags
    - hspec
    - genvalidity-containers
    - genvalidity-hspec
    - genvalidity-text

  mtags-doctest:
    main:                test/doctest-driver.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mtags
    - doctest
    - doctest-driver-gen
