name: Haskell Nix CI

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v18
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

    - name: Cachix setup
      uses: cachix/cachix-action@v12
      with:
        name: dbaynard
        signingKey: ${{ secrets.CACHIX_SIGNING_KEY }}

    - name: Nix build and test
      run: nix build -L
